Ajout de la page sur les refs
mcorbin/tour-of-clojure pull request #1
Opened 2020-05-02 08:17 UTC by arnaudgeiser

ClojureScript ne supportant pas les refs, la proposition est d'utilisation de CodeMirror plutôt que klipse afin d'avoir un affichage identique au détriment d'un code interactif.

Il existe encore un problème de font-size sur la page des refs. La font étant à la taille de 17px plutôt que de 15.3px.

2020-05-04 21:19 UTC, mcorbin requested changes

2020-05-04 21:19 UTC, mcorbin commented on src/tourofclojure/pages/ref.clj
> +          [:p "Pour intéragir avec une ref, il est nécessaire de se trouver dans une transaction dans la STM, ceci s'effectue grâce à "
Je reformulerais  en deux phrases: `Pour interagir avec une ref, il est nécessaire de se trouver dans une transaction dans la STM. Ceci s'effectue grâce à...`

2020-05-04 21:19 UTC, mcorbin commented on src/tourofclojure/pages/ref.clj
> +          [:p "Si l'ordre dans lequel s'effectue les opérations n'a pas d'importance, il est alors possible d'utiliser " [:b "compute"]]
s/compute/commute/g :D

2020-05-04 21:19 UTC, mcorbin commented on src/tourofclojure/pages/ref.clj
> +          [:p "Les transactions pouvant potentiellement se relancer plusieurs fois, leur utilisation n'est pas recommendée pour les opérations qui provoquent des effets de bord (I/O)."]]
typo: recommandée

2020-05-04 21:19 UTC, mcorbin commented on resources/public/pages/code/ref.clj
> +;; commute can be used if the order of the operations in the transaction does not matter
je reformulerais en "order of the operations between transactions"

2020-05-04 21:19 UTC, mcorbin commented
Merci beaucoup pour ta contribution !

J'ai fait quelques commentaires, mais sinon c'set otut bon ;)

2020-05-05 05:01 UTC, arnaudgeiser commented
Les adaptations ont été effectuées.

2020-05-09 10:14 UTC, mcorbin commented
Merci ;)

2020-05-09 10:14 UTC, merged