Ajout des pages sur les agents et core-async
mcorbin/tour-of-clojure pull request #3
Opened 2020-05-10 10:02 UTC by arnaudgeiser

Ajout des pages pour les agents et core-async.

Les sujets abordés dans core-async sont ceux que j'ai jugés les plus utiles et que j'aurais souhaité connaître lorsque j'ai commencé.

En attente de ton retour sur ces sujets, tant sur la forme que sur le contenu.

2020-05-10 15:30 UTC, mcorbin requested changes

2020-05-10 15:30 UTC, mcorbin commented on src/tourofclojure/pages/agent.clj
> +          [:p "La différence entre " [:code "send-off"] " et " [:code "send"] " est subtile. " [:code "send-off"] " envoie une action sur un pool de threads non borné alors que " [:code "send"] " aff
Je reformulerais cette partie en

```
[:p "La différence entre " [:code "send-off"] " et " [:code "send"] " est subtile. " [:code "send-off"] " envoie une action qui sera exécutée sur un thread dédié alors que " [:code "send"] " effectuera son opération sur un pool de thread interne à Clojure."]
```

2020-05-10 15:30 UTC, mcorbin commented on resources/public/pages/code/agent.clj
> +; Agent never blocks and the current value is readed
`and the current value can be read`.

2020-05-10 15:30 UTC, mcorbin commented on resources/public/pages/code/agent.clj
> +; Dereference the agent gives the current value
`Dereferencing`

2020-05-10 15:30 UTC, mcorbin commented on src/tourofclojure/pages/core_async.clj
> +          [:p "La valeur peut être lu d'un channel grâce à " [:code "&lt;&lt;!"] " (bloquant) et respectivement" [:code "&lt;!"] "(non bloquant)"]
`Les valeurs contenues dans un un channel peuvent être consommées grâce à ..`

2020-05-10 15:30 UTC, mcorbin commented on src/tourofclojure/pages/core_async.clj
> +          [:p "Les symbols non bloquants ("[:code "&lt;!"]" et " [:code ">!"] ") ne peuvent être utilisés que dans des go blocks. Un go block est unité de d'éxécution qui va être traitée par un pool
`Un go block est une unité d'exécution qui sera traitée par un pool de threads.`

2020-05-10 15:30 UTC, mcorbin commented on src/tourofclojure/pages/core_async.clj
> +          [:p "Les symbols non bloquants ("[:code "&lt;!"]" et " [:code ">!"] ") ne peuvent être utilisés que dans des go blocks. Un go block est unité de d'éxécution qui va être traitée par un pool
symbols => symboles

2020-05-10 15:30 UTC, mcorbin commented on src/tourofclojure/pages/core_async.clj
> +    (Thread/sleep 1000)
Par contre ça ça bloquera le thread, il ne faut pas appeler Thread/sleep dans un go block.

2020-05-10 15:30 UTC, mcorbin commented on src/tourofclojure/pages/core_async.clj
> +  (loop []
Il vaut mieux utiliser https://clojuredocs.org/clojure.core.async/go-loop je pense.

2020-05-10 15:30 UTC, mcorbin commented on src/tourofclojure/pages/core_async.clj
> +; Produces 1 every second
Dans tout cet exemple, utiliser go-loop est sûrement mieux.

2020-05-10 15:30 UTC, mcorbin commented on src/tourofclojure/pages/core_async.clj
> +    [:p [:a {:href "https://github.com/clojure/core.async/blob/master/examples/walkthrough.clj"} "core.async Walkthrough"]]]
Il manque `(navigation-block previous next)` à la fin de cette page.

2020-05-10 15:30 UTC, mcorbin commented
merci encore une fois pour ta contribution ;)
J'ai fait quelques commentaires sur la PR.

2020-05-10 16:17 UTC, arnaudgeiser commented on src/tourofclojure/pages/agent.clj
> +          [:p "La différence entre " [:code "send-off"] " et " [:code "send"] " est subtile. " [:code "send-off"] " envoie une action sur un pool de threads non borné alors que " [:code "send"] " aff
C'est peut-être mieux, effectivement. Je modifie.

2020-05-10 16:18 UTC, arnaudgeiser commented on src/tourofclojure/pages/core_async.clj
> +          [:p "La valeur peut être lu d'un channel grâce à " [:code "&lt;&lt;!"] " (bloquant) et respectivement" [:code "&lt;!"] "(non bloquant)"]
Effectivement, c'est peut-être mieux.

2020-05-10 16:27 UTC, arnaudgeiser commented on src/tourofclojure/pages/core_async.clj
> +  (loop []
Le but ici était de ne pas introduire trop de constructions et rester sur les primitives de base, quitte à avoir plus de code.
Je modifies, mais faut-il parler de go-loop dans les explications?

2020-05-10 16:28 UTC, arnaudgeiser commented on src/tourofclojure/pages/core_async.clj
> +    (Thread/sleep 1000)
Clairement.
Mais ça fait soit introduire la fonction timeout, soit introduire la fonction thread avant d'en parler.
Je fais les modifications, mais il faudra peut-être revoir la structure pour le coup.

2020-05-10 16:29 UTC, arnaudgeiser commented on src/tourofclojure/pages/core_async.clj
> +    [:p [:a {:href "https://github.com/clojure/core.async/blob/master/examples/walkthrough.clj"} "core.async Walkthrough"]]]
Je rajoute, et je profite pour le mettre également sur la page des atoms.

2020-05-10 16:45 UTC, arnaudgeiser commented
Les changements demandés ont été réalisés.
Je me demande tout de même si il ne faudrait pas expliquer ce qu'est un "go-loop" et "timeout".

2020-05-13 21:24 UTC, mcorbin commented on src/tourofclojure/pages/core_async.clj
> +  (loop []
Non, comme cela c'est OK

2020-05-13 21:25 UTC, mcorbin commented
>  Je me demande tout de même si il ne faudrait pas expliquer ce qu'est un "go-loop" et "timeout".

Pourquoi pas, mais ça peut être fait plus tard.

2020-05-13 21:25 UTC, merged